language: node_js
 node_js: node
 cache:
   directories:
     - node_modules
 script:
   - npm test
 env:
   - CI=true

 before_deploy:
   - npm install netlify-cli -g
   - npm run build

 deploy:
   provider: script
   script: netlify deploy -s clever-chandrasekhar-5a0660 -t ddcee3b0-9e8a-47e6-85a2-95eee34d0608 -p ./build
   skip_cleanup: true
   on:
     branch: master
